### ISSUE TITLE
Zápisnice

### ISSUE THREAD

**Issue by rtoth94** [TIS2017/MiestnostiVKostole#1]

**Comment by pavelpetrovic** [comment]
Dobrý deň,

ďakujem za pridanie zápisníc. Wordovské dokumenty sú dosť nepraktické. 
Mohli by ste, prosím, písať zápisnice rovno na githubovú wiki - a to hneď na stretnutí a na konci stretnutia to uložiť? Zápisnice sú predovšetkým pre vás, aby ste sa mohli pozrieť na čom ste sa na stretnutí dohodli. Okrem toho majú zápisnice obsahovať konkrétne informácie, nielen veľmi všeobecné body, za ktorými si možno predstaviť hocičo. Vaša tímová komunikácia by mala ísť predovšetkým cez issues a cez zápisnice. 

čiže - vymazať zápisnice z repozitára, zrušiť branch zápisnice, vytvoriť ich na wiki a ďalšie zápisnice písať priamo na stretnutí a podrobne. pozrite si ako to robia mnohé iné tímy.

Ďakujem,
Pavel.
