### ISSUE TITLE
Testovacie scenáre

### ISSUE THREAD

**Issue by kkikus** [TIS2017/MiestnostiVKostole#14]

**Comment by andrejjursa** [comment]
Prva verzia tvori fajn zaciatok, avsak:

- [ ] kazdy testovaci scenar musi referencovat poziadavky (podla ich cisiel) z katalogu poziadaviek, aby bolo jasne, ktoru poziadavku testuje,
- [ ] vacsina vasich testov bohuzial skonci pri tom, ze sa nieco zobrazi, to je sice fajn ale co testy k tomu, ze sa nieco stane, ako napr. ze ak kliknem na potvrdenie ziadosti o vstup do skupiny tak vysledok je bud pridanie do skupiny, asi ak neprekrocila nejaky limit (ci sme bez limitov?) alebo zamientutie ak je dosiahnuty limit,
- [ ] nikde nie je jasne, co je v teste povazovane za uspech, pricom chcem pripomenut, ze zobrazenie chybovej spravy v pripade chybneho vstupu je uspech a nie neuspech testu, neuspech by to bol vtedy, ked je vsetko ok a dostanem chybove hlasenie, alebo je vstup nespravny a proces aj tak "uspesne" skonci bez chyboveho hlasenia,
- [ ] ak je iba jedne ukon v testovacom scenari, preco je vsade `Ukon-` a nie len `Ukon`?

**Comment by kkikus** [comment]
@andrejjursa môže to byť takto? Dúfam, že to je lepšie.
