### ISSUE TITLE
Katalóg poziadaviek

### ISSUE THREAD

**Issue by rtoth94** [TIS2017/MiestnostiVKostole#4]
Prvá verzia

**Comment by andrejjursa** [comment]
@TIS2017/teamtis1 az budete mat pdf verziu, prosim dajte mi vediet, aby som sa na nu mohol pozret a skontrolovat, az po mojom schvaleni moze ist dokument dalej zadavatelke, dakujem.

**Comment by andrejjursa** [comment]
E-mailom som dostal pdfko druhej verzie katalogu poziadaviek, takze vam vsetkym @TIS2017/teamtis1 sem napisem pripomienky:

1. struktura dokumentu nie je v sulade so strukturou z prednasky (http://dai.fmph.uniba.sk/courses/tvorbaIS/tis/new.html, cast 2.1), v casti 1 vasho dokumentu chybaju casti 1.4 a 1.5 a cast 2 je spojena s castou 3, tiez tam nie su vsetky nalezite casti z prednasky
2. ak je to mozne, skuste do casti 1.2 dopisat nejaky suhrn kolko asi roznych samostatnych obrazoviek (alebo ako to nazvat - stranok?) bude aplikacia obsahovat, aby bolo mozne lepsie si predstavit jej rozsah, ktory bude vnimat pouzivatel + ake casti, ktore ziaden pouzivatel nevidi (backend) aplikacia obsahuje, bude potom lepsie mozne si predstavit jej rozsah, funkcie su tam opisane zrejme dostatocne teraz
3. 1.3 (a dalej) - prosim pouzivajte slovo pouzivatel (uzivatel je z cestiny, to sa skor pouziva v hovorovom prejave ale nie v technickom dokumente, ktorym tento katalog je), potom tiez slovne spojenie s najvacsimi pravami, ked uz s najvyssimi pravami, este celkovo k 1.2 a 1.3 (a asi aj dalsim zoznamom ak v dokumente su, citam to postupne z hora dolu a rovno pisem ...) v slovencine konci prvok zoznamu ciarkou a nie bodkou, bodka sa dava na koniec posledneho prvku ak nim text konci (a samozrejme, pouzivajte jednotny styl zoznamov, nie ze na jednej strane su dva rozne, posobi to zle)
4. doplnte referencie (cast 1.4) a prehlad dokumentu (cast 1.5)
5. teraz pozeram, ze cast 2 (celkovy opis - mimochodom pri cislovanii sekcii dokumentu sa nedava bodka za posledne cislo) je priamo cast 3 z prednasky a ma sa volat Specificke poziadavky, cast 2 Vseobecny popis si asi spravila dovolenku, ale bolo by velmi ziaduce, aby sa z nej vratila, inak dokument neuznam
6. 2.1 Hlavny ciel, takyto bod v dokumente neexistuje, teoreticky by sa dalo zapracovat do bodu 2.2 Funkcie produktu, ale ani tam mi to uplne nesedi
7. bod 2.2 Triedy pouzivatelov koresponduje s obsahom bodu 2.3 Charakteristika pouzivatelov (z prednasky), este by mohlo byt velmi vhodne sem doplnit UML Use-Case diagram pre lepsiu vizualnu predstavu o opravneniach jednotlivych typov pouzivatelov
8. od bodu 2.3 vo vasom dokumente to uz vyzera na vymenovavanie poziadaviek, nicmenej, toto ma byt v casti 3 dokumentu a jednotlive poziadavky nemaju byt v subsekciach ale oznacovane napr. znacenim R-## kde ## je cislo poziadavky, pripadne rekurentne R-##-## ak je mozne specifikovat detailnejsie subpoziadavky nadradenej poziadavky (to sa da skoro vzdy)
9. z toho co vsetko zadavatelka k projektu povedala je napisanie dokopy 5 poziadaviek na jednu stranu dost malo, chcem aby dokument vycerpavajuco opisal vsetko, technicky a jedno-jednoznacne zapisane a ocislovane, granularne delene vacsie celky na mensie poziadavky, tym docielime jasny a zrozumitelny vyklad o obsahu a funkcionalite finalneho softwaru

A este k celemu dokumentu, na viacerych miestach som si vsimol, ze chybali vo vetach ciarky na miestach, kde mali byt ...

Tento dokument este zadavatelke samozrejme naposielajte, dajte tuto verziu do gitu a spiste novu verziu, ktoru tiez date do gitu a poslete mi mention s cislom commitu. 

vdaka, drzim palce!

**Comment by andrejjursa** [comment]
Nez sa pustim do hodnotenia dalsej verzie katalogu poziadaviek, musim vas upozornit na jeden problem. Na uvode sme hovorili o issue a feature branch cislovanych podla issue a rovnako tak commitoch referovanych k ID issue. Vy nerobite nic z toho. Mate jedinu branch, Dokumenty, v ktorej su dve pdfka, zjavne commitnute v jednom commite a bez identifikacie issue. To, ze su tam iba pdfka samozrejme je v poriadku, co v poriadku nie je, je commit oboch verzii naraz, popravde, nechapem naco to cislujete, keby ste s gitom pracovali spravne, mohol sa subor volat katalog_poziadaviek.pdf a jeho verziu by urcoval popis v commite. Skorsiu verziu by si kazdy nasiel v historii. Bol by som rad, aby ste git pouzivali ako sa ma a nie ako ftp server. V opacnom pripade sa to moze v konecnom zuctovani prejavit na vasom hodnoteni.

Teraz k tretej verzii katalogu poziadaviek:

* dokument nema cislovane strany, zjavne skryte cislovanie zacina na titulnej strane ale ma zacinat na strane, kde sa nachadza uvod,
* hlavne sekcie, oznacene jednym cislom, sa cisluju bez bodky!, tj. nie `1. Uvod` ale `1 Uvod`,
* table of contents (Obsah) nie je aktualizovany a chybaju v nom subsekcie niektorych sekcii,
* na niektorych miestach je dokument pisany hovorovim stylom, co je nepripustne, pokusim sa konkretne miesta uviest v nasledujucom zozname.

Zoznam sekcii jedna po druhej:

1. **1.1 Cliel dokumentu** - `pre administráciu miestnosti` asi nie jednej ale viacero, takze doplnit dlzen, specifikacia sluzi aj pre zadavatela, na kontrolu vysledneho produktu, technicky to tam je napisane len v zvlastnom poradi,

1. **1.2 Rozsah projektu** - stale nie je uplne jasny rozsah, aj ked teraz je uz lepsie vidiet niektore detaily, nicmenej par veci:
    * prosim najprv napisat uvodnu vetu, mozno v tvare `Vysledna aplikacia bude pozostavat z tychto casti:` a potom az tento zoznam,
    * v zozname by mali vsetky prvky zacinat malym pismenom,
    * popis weboveho servra ak, ze tam bezi aj databazovy server, a ze sa zaobera autentifikaciou je scestny, v prvom rade nie je tu jasne co sa mysli slovom server a pojem webovy server (apache2? ci nginx?, tomcat? alebo co ja viem aky iny) nie je vobec vysvetleny, pisat, ze na nom bezi databazovi server je proste nepravda, to ako mysql pobezi pod apache2 ci ako?,
    * mapku vsade oznacujte slovom mapa prosim,
    * nie je graficke rozhranie nahodou sucast webovej stranky? alebo webova aplikacia bude terminalova?

1. **1.3 Slovnik pojmov** - opat jedno po druhom:
    * Administrator je snad spravca systemu, ano ma najvyssie opravnenia ale ten popis je uplne detinsky,
    * Notifikacia - co je to prosim vas zmenena udalost?
    * Server - co to je, chapeme to ako hardware alebo software? nie je jasne co sa mysli, mozno najlepsie by bolo specifikovat vsetky druhy serverov samostatne (server ako hw, databazovy server, webovy server),
    * Databaza sice obsahuje informacie, udaje a data, co je mimochodom vsetko synonimum s rovnakym vyznamom, ale s popisu nie je jasne co to je, ona totiz databaza moze byt aj kartoteka v skrynke a ta sotva bude fungovat s nejakou webaplikaciou,
    * Podorys - miesto predmetu by bolo lepsie napisat objektu,

1. **1.4 Referencie** - to je sice pravda, co je tu napisane, nicmenej bude to webova aplikacia, takze by mohla mat referencie na webove technologie aspon, alebo snad na jej realizaciu vytvorite nove web technologie, vlastne prehliadace, vlastny jazyk na popis online dokumentov, vlastny server a vsetko svoje, takze zacinate uplne od nuly a nestaviate na nicom existujucom?

1. **1.5 Prehlad dokumentu** - toto nie je kniha a tak nema kapitoly, ma sekcie alebo casti ak to chceme striktne slovensky, opravte to, cast vety `alebo systém používať` prosim vypustite, to znamena to iste, ze budu so systemom pracovat, zrejme mate tendenciu zdvojovat informacie aby ste nafukly text, ale to je zla praktika, inak je obsah sekcie ok,

1. **2.1 Kontext systemu** - prva veta je zjavne nedokoncena, predpokladam, ze to chcelo byt suvetie vysvetlujuce ucel aplikacie, niekde by sa tu malo pisat o skutocnom kontexte, teda pre koho je aplikacia urcena a v akom spolocenskom prostredi sa ma pouzivat,

1. **2.2 Funkcie systemu** - prosim vas tu a aj inde, kde sa to nachadza, nepouzivajte znak `/` ale priamo pouzite spojku `alebo`, ovela lepsie sa to cita, druha vec je naduzivanie spojky `ze`, mate ju v niekolkych po sebe iducich vetach, prosim vas, nahradte ju inymi spojkami, ktore sa nebudu opakovat stale za sebou, aby sa text lepsie cital,

1. **2.3 Charakteristika pouzivatelov** - ten Use-Case diagram tu nevidim, dalej:
    * mapka nech je mapa,
    * `v ktorej je on zaradený` zmenit na `v ktorej je zaradený` (tj. vyhodit zbytocne zameno),
    * `/` nahradit za `alebo`,
    * `ktorý jeho úlohou je schvaľovať žiadostí` opravit sklonovanie,
    * `ktorý jeho úlohou je vytvárať a zrušiť skupiny` dvakrat tak isto podivne sklonovanie, opravit prosim,
    * `Vytvoreným skupinám prideľuje miestnosti a čas, v ktorom sa tam budú môcť nachádzať.`  - skuste to napisat tak, aby z toho bolo jasne, co bude robit, toto vyzera ako keby administrator rozhodoval o kvantovom stave exitencie miestnosti v case, to asi robit nebude ...,
    * `nadbytočnými vecami` prepisat na `nadbytočnými úkonmi`,

1. **2.4 Obmedzenia** - to je sice pekne, ked si to po sebe precitate tak vas iste do oci udrie to `ze`, ale toto tam pisat nemozete, ci uz mate alebo nemate nieco taketo vysporiadane, stale ste schopny nejake vseobecne obmedzenia identifikovat, napr. som si pomerne isty, ze obmedzite aplikaciu na beh na systeme linux, ze aplikacia ma bezat vo webovom prehliadaci (racionalne povedane viacerych prehliadacoch, predpokladane od nejakych verzii vzhladom na planovane pouzite webove technologie - client side - tj. css, html, javascript), takze obmedzenia sa napisat daju, veticku co tam mate zruste a poriadne sa zamyslite co tam miesto toho dat,

1. **2.5 Predpoklady a zavislosti** - nie, nie, a nie, tu sa ma pisat o predpokladanych zavislostiach, tj. o type weboveho servra, operacneho systemu, aplikacnych technologiach (je tu spomenute iba PHP), aka asi databaza tam bude, ak uz viete, ze to bude php, tak predpokladane frameworky, kniznice a pod.,

1. Poziadavky v sekcii **3 Specificke poziadavky** - dajme tomu, ze prizmurim oko nad tym, ako ich cislujete (tj. iba podla cisla sekcie, co nie je stastne), hoci som vam to v minulom komentari v bode 8. napisal, ako sa to robi, horsie je ako stroho poziadavky popisujete, napr. uz prva **3.1.1 Administracia systemu** je prikladom scela zleho specifikovania poziadavky, nie len, ze to co je tu napisane nedava absolutne ziadnu predstavu o tom, co treba implementovat, ale je to popisane jedinou vetou, hoci administracia systemu je zjavne velka cast aplikacia a teda je nutne tuto poziadavku delit na viacero mensich a dokladne opisanych (co, kde, ako sa robi v systeme v administratorskom rozhrani), to samozrejme plati aj pre **3.1.2**, **3.1.3**, **3.1.4**, **3.1.5** a mozem takto pokracovat, cize zhrnutie sekcie **3** je nasledovne: **zamietam**, toto nie je specifikacia poziadaviek! treba to napisat tak, aby ked si to precita niekto nezainteresovany, tak bude vediet co a ako ma system robit.

Uvedomte si prosim, ze cielom tohoto predmetu nie je pisat omacky a potom nieco nakodit, ale seriozne pristupovat k specifikacii, navrhu, implementacii a testovaniu softwaroveho diela v mensej skupine autorov. Dokial specifikacia nebude spravna, nepohnete sa dalej, a ak vam ju budem dokola zamietat kvoli chybam, tak sa k ostatnym castiam prace na projekte ani nedostanete a vysledok bude neslavny. Takze, poprosim vas, aby ste k projektu pristupovali zodpovedne a so vsetkou vaznostou a odovzdali pracu, ktora splna ocakavane naroky.

Dakujem za pochopenie a prajem vela zdaru pri upravovani katalogu poziadaviek.

PS: nezabudnite, co som na uvod pisal o pouzivani gitu.

**Comment by andrejjursa** [comment]
@rtoth94 preco je ten dokument zrazu v roote a nie v adresari Dokumentacia ako boli tie pdfka predtym?

**Comment by rtoth94** [comment]
Ups...tak spravim to znova, ale takto bude fajn, ze ked davam len referenciu na issue, a stale ten novy subor ked nieco menime?

**Comment by andrejjursa** [comment]
@TIS2017/teamtis1 deje sa nieco s tymto katalogom alebo to stoji na mrtvom bode?

**Comment by andrejjursa** [comment]
@TIS2017/teamtis1 Hodnotenie zatial poslednej verzie s pred 7 dni:

- [ ] **sekcia 2.3** stale je tam ten chybny Use-case diagram, ako moze bezny pouzivatel, napriklad, pri prihlaseni sa do skupiny zahrnat aj schvalovanie ziadosti? Znacka `<<include>>` ma iny vyznam, ide o zahrnutie jedneho pripadu pouzitia do druheho a teda z tohoto vyplyva nepravda, kde bezny pouzivatel si vie sam schvalit ziadost o pripojenie do skupiny, prosim opravte si to a ked to budete prepisovat, tak pri tom trochu rozmyslajte,
- [ ] **sekcia 2.5** tu je priam hrozostrasny chaos, chcelo by to rozdelit na niekolko viet, jedno dlhe suvetie je zle citatelne, pozn. k webovym prehliadacom, co tak apple safari, microsoft edge? opera nic? nehovoriac o tom, ze ani nepisete o platforme a pokial viem tak tato appka ma behat hlavne na smartfonoch, o tom tu nie je ani slova, technicky mate dve mobilne platformy, ios a android, ostatne je minoritne (kolko percent ma windows 10 na smartfonoch?), toto si dajte do poriadku
- [ ] **sekcia 3.1** poziadavka **1.1.1** nazov je administracia systemu a popisuje sa tu pouzivatel administrator, nehovoriac o tom, ze tato poziadavka vobec nehovori o tom, co administracia systemu je, je tu len kopa nezmyselnych viet v jednom velkom odstavci. Preco je to nezmyselne? Chcete jednou poziadavkou obsiahnut vsetko co sa tyka administracie a to sa neda. Toto treba rozbit na mensie poziadavky na jednotlive casti, nepisat tam "Ked je administrator prihlaseny moze to, to a to" ale samostatne mensie celky a popisat, co sa v nich nachadza a aky maju ucel, ked sa tam nieco deje, tak ako, ak sa operacia podari tak co potom, a ak sa nepodari, tak co potom,
- [ ] **sekcia 3.1** poziadavka **1.1.2** toto je to iste co **1.1.1**, na to aby aplikacia dokazala spracovavat to, co ma tento naduzivatel robit, musi obsahovat niekolko casti, kazda je samostatna poziadavka, ktora musi vysvetlit, co, ako, kde, co ak je proces ok a co ak nie je ok,
- [ ] **sekcia 3.1** poziadavka **1.1.3** opat, vela poziadaviek v jednej, rozdelit,
- [ ] **sekcia 3.1** poziadavka **1.1.4** toto vobec nedava zmysel, treba to upravit tak aby bolo jednoznacne, ako ma aktualizacia stranok fungovat, nehovoriac o tom, ze pisete o aktualizacii stranok ale poziadavka evidentne cieli na samotnu mapu,
- [ ] **sekcia 3.2** poziadavka **1.2.3** dalsia poziadavka, ktora kombinuje privela poziadaviek do jednej, toto sa musi rozdelit, naviac ani nie je vysvetlene ako napr. sa dostanem k harmonogramu pre dany tyzden, je treba niekde kliknut? je treba pouzit formular filtra? je treba si nasadit na hlavu elektrody a aplikacia to precita z mojej mysle :)? ako? vacsina vasich poziadaviek je napisana formou "domysli si sam", ale takto to bohuzial nefunguje,
- [ ] **sekcia 3.2** poziadavka **1.2.4** opat mame viacero poziadaviek v jednej, toto sa da rozdelit na grafiku webu, grafiku mapy, co grafika administracie?, poziadavka na jednoduchost je viac-menej samostatna,
- [ ] **sekcia 3.2** poziadavka **1.2.5** kedy sa zobrazia informacie o skupine?, to iste co poziadavka **1.2.3**, kontaktne udaje na veduceho sa zobrazia kazdemu ci iba prihlasenemu pouzivatelovi? Telefonne cislo a e-mail sa daju povazovat za osobne udaje, rovnako tak meno je osobny udaj a mena vsetkych clenov skupiny, to by asi nemal vidiet nikto okrem celnov skupiny, alebo tato aplikacia na ochranu osobnych udajov neprihliada? Toto by ste si mali vykonzultovat so zadavatelkou, ak neviete presne, ako to ma byt,
- [ ] na zaver vas prosim, aby ste si to po sebe precitali, pozorne precitali, a opravili chyby v slovoslede a preklepy a tak isto by bolo naozaj dobre opravit vsetky vety tak, aby nezneli ako keby ich pisal niekto, kto mal aktualne vypite.

Celkova poznamka: vasou ulohou je poziadavky napisat tak, aby ked to chyti do ruky niekto, kto o tomto projekne nevie vobec nic, bol schopny zadaniu projektu a jeho zmyslu porozumiet. Tento dokument to nesplna, ani ja z neho presne nechapem co a kde a ako bude fungovat a to som bol na stretnuti so zadavatelkou s vami. Rad by som bol, aby ste sa nad dokumentom hlboko zamysleli, presli si vsetky poziadavky, upravili ich tak aby boli jednoznacne, potom ich presli opat a rozmyslali, ci tam nieco nechyba, nie je tam nieco navyse ale **hlavne!!!** ci to vsetko dava zmysel a je to konzistentne. Necakajte, ze ked si to pozrie zadavatelka tak hned bude vidiet vsetky chyby co v dokumente su (nemyslim tie stylisticke a gramaticke) a upozorni vas na ne. Zber a zapis poziadaviek je faza, ktora nesmie byt v ziadnom pripade podcenena. Ak nieco vam nie je jasne, tak sa treba stretnut so zadavatelkou znovu.

**Comment by andrejjursa** [comment]
@TIS2017/teamtis1 snad posledny posudok,

takze:
- [ ] **sekcia 2.5** - este tam stale nie je informacia o platformach iOS a Android
- [ ] **poziadavka 1.5.2** - hovori o moznosti kombinacie typov filtrov, jednotlive podpoziadavky sa ale zdaju byt uplne separatne a nezlucitelne filtracie s ostatnymi typmi, hlavne **1.5.2.1** preco otvara zoznam na novej karte? este to prosim trochu premyslite
- [ ] **sekcia 3.2** - niektore poziadavky su redundantne, popisuju to iste a zaradene su do viacerych casti (ako Miestnost, Grafika, Skupiny), prakticky to nevadi pri tomto pocte poziadaviek, teoria ale radi redundancii sa vyhybat, tak porozmyslajte, ci to nejak neupratat

este raz si dokument nakoniec po sebe, vsetci styria, precitajte a korigujte slovosled, sklonovanie a pod. problemy, ktore sa v texte obcas vyskytnu

prosim aby ste dali dokument do adresara dokumentacia (ci ako ste ho nazvali) a nie aby bol v root adresari ako teraz, a nazvite ho normalne katalog_poziadaviek.pdf a nie KP.pdf
